### ISSUE TITLE
Crashes on startup, doesn't work on IJ 2024.2 (K2 mode)

### ISSUE THREAD

**Issue by skaldebane** [rustamsmax/compose-highlighter-plugin#3]
Hi there!
This plugin was unsupported on 2024.2 in K2 mode for a while, until the latest update.

However, it now crashes on startup with this error, and the colors don't get applied.

```
java.lang.IllegalStateException: Cannot find service org.jetbrains.kotlin.caches.resolve.KotlinCacheService (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Kotlin, id=org.jetbrains.kotlin, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate/plugins/Kotlin, version=242.23339.11-IJ, package=org.jetbrains.kotlin, isBundled=true), packagePrefix=org.jetbrains.kotlin., state=active, parents=PluginDescriptor(name=Java, id=com.intellij.java, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate/plugins/java, version=242.23339.11, package=null, isBundled=true), ), serviceContainer=Project(name=REDACTED, containerState=COMPONENT_CREATED, componentStore=/home/skaldebane/Projects/REDACTED), serviceContainerClass=com.intellij.openapi.project.impl.ProjectImpl)
	at com.intellij.openapi.components.ServicesKt.serviceNotFoundError(services.kt:38)
	at org.jetbrains.kotlin.caches.resolve.KotlinCacheService$Companion.getInstance(KotlinCacheService.kt:43)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.analyzeWithAllCompilerChecks(ResolutionUtils.kt:169)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.analyzeWithAllCompilerChecks(ResolutionUtils.kt:165)
	at uz.rsteam.intellij.plugin.KMPComposableAnnotator.highlight(KMPComposableAnnotator.kt:45)
	at uz.rsteam.intellij.plugin.KMPComposableAnnotator.annotate(KMPComposableAnnotator.kt:35)
	at com.intellij.codeInsight.daemon.impl.AnnotationHolderImpl.runAnnotatorWithContext(AnnotationHolderImpl.java:216)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotator$2(AnnotatorRunner.java:129)
	at com.intellij.codeInsight.daemon.impl.AnnotationSessionImpl.computeWithSession(AnnotationSessionImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.runAnnotator(AnnotatorRunner.java:119)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotatorsAsync$0(AnnotatorRunner.java:66)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:279)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotatorsAsync$1(AnnotatorRunner.java:66)
	at com.intellij.concurrency.ApplierCompleter.processArrayItem(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.processArray(ApplierCompleter.java:196)
	at com.intellij.concurrency.ApplierCompleter.execAll(ApplierCompleter.java:166)
	at com.intellij.concurrency.ApplierCompleter.lambda$exec$0(ApplierCompleter.java:105)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$2(ApplierCompleter.java:148)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:159)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapAndRun$1(ApplierCompleter.java:140)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.concurrency.ApplierCompleter.wrapAndRun(ApplierCompleter.java:140)
	at com.intellij.concurrency.ApplierCompleter.exec(ApplierCompleter.java:108)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

```

**Comment by rsktash** [comment]
Hi, will be fixed in an upcoming update

**Comment by biberesser** [comment]
Hi there, ist there any news on the subject?

This plugin ist really nice, but I miss the huge K2 performance improvements.

They are solving this exact error here:
https://www.youtube.com/live/HDyWQLNMJQ8?si=YEGw2p-yb21nRl3K

**Comment by skaldebane** [comment]
Hi again! Any updates here? This issue shouldn't have been closed without a PR tbh.

Is this plugin even maintained anymore? I see the latest commit was 2 years ago.
